Repository aritra0342/Resume_generator, pull requests merged in 2025-03, with the labels that each got.

#8 Fix #3: Headings no longer display on resume if fields are empty
  script.js
Labels: apertre2.0, Easy

#10 Added DOCX export functionality
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy, doc

#12 Indicate required fields
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#14 Adding the extra button in form to add the profile picture of a candidate
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#18 Added character limits to resume fields to improve layout
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy, doc

#20 Fix issues caused by previous PR #18
  index.html
  script.js
  style.css
Labels: apertre2.0

#24 Enhace certificate input field and add link option
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#30 Fix Overlap of Upper Form Elements and Add Interactive Hover Effects for a Clearer Layout. #29
  index.html
  style.css
Labels: apertre2.0, Easy

#33 Remove Resizing of Textareas and UI Enhancement
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#35 Fix #2: Enhance UI
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#34 Updated PR for transition between dark and light modes
  README.md
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#41 Add landing page to the "Resume Generator" project.
  index.html
  landing-page.css
  landing-page.html
Labels: apertre2.0, Easy

#42 Enhance the UI
  images/background.png
  images/favicon.png
  index.html
  script.js
  style.css
Labels: apertre2.0, Easy

#43 Added back to top button
  style.css
Labels: apertre2.0, Medium

#45 Did small change for asterisk remover
  script.js
Labels: apertre2.0, Easy

#48 Add Real-Time Resume Preview Feature
  index.html
  script.js
  style.css
Labels: apertre2.0, Medium

#47 Improved UI of landing page
  images/background-landing.jpg
  landing-page.css
  landing-page.html
Labels: apertre2.0, Easy

#51 FIX: Keep Live Preview Box Sticky & Improve Form Layout (Issue No #50)
  script.js
  style.css
Labels: apertre2.0, Easy

#52 Add Hover Effects
  index.html
  style.css
Labels: apertre2.0, Easy

#54 Enhanced Auto-Save Feature for Resume Form (Like Google Forms) –to Retain Data on Refresh #53
  script.js
Labels: apertre2.0, Medium

#49 add navbar to the Resume Generator Project
  index.html
  landing-page.css
  landing-page.html
  style.css
Labels: apertre2.0, Easy

#65 PR and Issues Templates added
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: apertre2.0, Easy
