Repository aritra0342/Resume_generator, pull requests merged in 2025-04, with the labels that each got.

#70 Template
  CONTRIBUTION.md
Labels: apertre2.0, Easy

#71 the-navbar-is-fixed-and-enhanced (Issue no- #63)
  index.html
  script.js
  style.css
Labels: apertre2.0, Medium

#74 Made the modification
  styles/landing-page.css
  styles/style.css
Labels: apertre2.0, Easy

#81 Implemented dynamic floating particle animation at the home-page background (Using Canvas API). ISSUE- #67
  pages/landing-page.html
Labels: apertre2.0, Medium

#77 SEO Optimised by adding Meta Tags
  pages/index.html
  pages/landing-page.html
  styles/landing-page.css
Labels: apertre2.0, Easy

#78 Position of Navbar fixed on Resume Creation Page
  styles/style.css
Labels: apertre2.0, Easy

#79 UI
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Easy

#80 adding signup and signin options
  images/register1.png
  images/register2.png
  js/Register.js
  pages/Register.html
  pages/index.html
  pages/landing-page.html
  styles/Register.css
Labels: apertre2.0, Medium

#76 Made the changes
  pages/index.html
  styles/landing-page.css
  styles/style.css
Labels: apertre2.0, Easy

#83 Enhanced the Form page background with dynamic animation using particles .js (Issue no- #82)
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Medium

#87 Enhance UI of the Register Page with Hover Effects for Social Media Icons & Auth Buttons. Issue no #84
  styles/Register.css
  styles/style.css
Labels: apertre2.0, Easy

#89 Made the changes
  pages/index.html
  styles/style.css
Labels: apertre2.0, Easy

#90 Responsiveness of website fixed
  pages/index.html
  pages/landing-page.html
  styles/landing-page.css
  styles/style.css
Labels: apertre2.0, Medium

#91 Fixed the main page layout and structuring (Issue- #88)
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Medium

#92 Navigation bar is implimented in the Register page. (Issue no- #86)
  pages/Register.html
  styles/Register.css
Labels: apertre2.0, Medium

#93 Footer Added
  pages/index.html
  pages/landing-page.html
  styles/Register.css
  styles/footer.css
  styles/landing-page.css
  styles/style.css
Labels: apertre2.0, Easy

#97 navbar-marge-on-scroll-fixed
  styles/style.css
Labels: apertre2.0, Easy

#98 Main page footer enhanced (ISSUE no-#95)
  pages/index.html
  styles/style.css
Labels: apertre2.0, Easy

#101 The footer section of the landing page improved .(ISSUE no- #99 ).
  pages/landing-page.html
  styles/landing-page.css
Labels: apertre2.0, Easy

#102 Update style.css
  styles/style.css
Labels: apertre2.0, Easy

#107 Multiple Entries
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Medium

#106 New Logo
  images/loggo.svg
  pages/Register.html
  pages/index.html
  pages/landing-page.html
  styles/landing-page.css
Labels: apertre2.0, Medium

#112 README
  README.md
Labels: apertre2.0, doc

#118 Favicon update
  README.md
  favicon/favv.png
  images/favicon.png
  images/readme logo.svg
  pages/Register.html
  pages/index.html
  pages/landing-page.html
Labels: apertre2.0, Easy

#120 Update README.md
  README.md
Labels: apertre2.0, Easy

#122 Fixed the Uneven structuring of different sections for the Form. (Issue -no #115)
  styles/style.css
Labels: apertre2.0, Medium

#123 Home page popover about card implemented. (Issue no-#117)
  pages/landing-page.html
  styles/landing-page.css
Labels: apertre2.0, Easy

#124 LogIn-SignUp UI
  images/1.svg
  images/2.svg
  pages/Register.html
  styles/Register.css
Labels: apertre2.0, Easy

#128 About Page Added
  pages/about.html
  pages/landing-page.html
  styles/about.css
Labels: apertre2.0, Easy

#132 FORM PAGE-about-section-attached ,It was missing.(Issue -no #125)
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Easy

#129 Contact Page Added
  pages/contact.html
  pages/landing-page.html
  styles/contact.css
Labels: apertre2.0, Easy

#131 Update the name and description section
  styles/style.css
Labels: apertre2.0, Easy

#133 Fix minor mistake in README
  README.md
Labels: apertre2.0, doc

#137 Added Custom Scrollbar
  styles/style.css
Labels: apertre2.0, Easy

#139 Minor changes in resume preview box position
  styles/style.css
Labels: apertre2.0, Easy

#141 Implemented back-to-top for the Form and got rid of the non functional page back to top button.(Issue no-#140)
  js/script.js
  pages/index.html
  styles/style.css
Labels: apertre2.0, Easy
